version: '3.2'
services:
  mosquitto:
    image: toke/mosquitto
    network_mode: "host"

  service:
    build:
      context: ./service
    network_mode: "host"
    restart: on-failure

  heater:
    build:
      context: ./heater
    network_mode: "host"
    restart: on-failure

  sensors:
    build:
      context: ./sensors
    network_mode: "host"
    restart: on-failure
